from django.urls import path, re_path
from app import views

urlpatterns = [
    path('addAssets/', views.addAssets.as_view(), name='add assets'),
    path('addAssetType/', views.addAssetType.as_view(), name='addassettypeapi'),
    path('addComment/', views.addComment.as_view(), name='addcomment'),
    path('addEmail/', views.addEmail.as_view(), name='addemail'),
    path('addIssue/', views.addIssue.as_view(), name='addissueAPI'),
    path('addPart/', views.addPart.as_view(), name='add part api'),
    path('addTechnician/', views.addTechnician.as_view(), name='addmechanicAPI'),
    path('addUser/', views.addUser.as_view(), name='adduserapi'),
    path('assignUser/', views.assignUser.as_view(), name='assignUser'),
    path('assignIssue/', views.assignIssue.as_view(), name='assignIssue'),
    path('assignTechnician/', views.assignTechnician.as_view(), name='assignTechnician'),
    path('changestatus/', views.changeTicketStatus.as_view(), name='changeticketstatus'),
    path('checkEmail/', views.checkEmail.as_view(), name='Check whether email can make account'),
    path('createTicket/', views.createTicket.as_view(), name='createticket'),
    path('dashboardCards/', views.dashboardCards.as_view(), name='dashboardcards'),
    path('dashboardGraphs/', views.dashboardGraphs.as_view(), name='dashboardgraphs'),
    path('delAssetType/', views.delAssetType.as_view(), name='deleteassettype'),
    path('delIssue/', views.delIssue.as_view(), name='Delete Issue.'),
    path('delPart/', views.delPart.as_view(), name='Delete part'),
    path('delTechnician/', views.delTechnician.as_view(), name='delTechnician'),
    path('delUser/', views.delUser.as_view(), name='deleteuser'),
    path('deletecomment/', views.deleteComment.as_view(), name='deletecomment'),
    path('deleteTicket/', views.deleteTicket.as_view(), name='deleteTicket'),
    path('editcomment/', views.editComment.as_view(), name='editcomment'),
    path('getAssetTypes/', views.getAssetTypes.as_view(), name='getAssetTypes'),
    path('getAssets/', views.getAssets.as_view(), name='getassets'),
    path('getComments/', views.getComments.as_view(), name='getcomments'),
    path('getIssues/', views.getIssues.as_view(), name='Get Issue Information.'),
    path('getNewTicketIndex/', views.getNewTicketIndex.as_view()),
    path('getNotifications/', views.getNotifications.as_view()),
    path('getParts/', views.getParts.as_view(), name="Get Parts"),
    path('getTechnicians/', views.getTechnicians.as_view(), name='getTechnicians'),
    path('getTicketInfo/', views.getTicketInfo.as_view(), name='getTicketInfo'),
    path('getTickets/', views.getTickets.as_view(), name='getTickets'),
    path('getUser/', views.getUser.as_view(), name='getuser'),
    path('getUsers/', views.getUsers.as_view(), name='getusers'),
    path('markRead/', views.markRead.as_view(), name='For Notifications'),
    path('predictionData/', views.predictionData.as_view(), name='predictionresults'),
    path('results/', views.searchForum.as_view(), name='forumresults'),
    path('updateSettings/', views.updateSettings.as_view(), name='updateSettings'),
    path('updateTicket/', views.updateTicket.as_view(), name='updateTickets'),
    path('uploadAssets/', views.uploadAssets.as_view(), name='uploadAssets'),
    path('uploadWorkTemplate/', views.uploadWorkTemplate.as_view(), name='Upload Linke for Work Template'),
    ]