# Generated by Django 3.1.4 on 2021-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
