# Generated by Django 3.1.4 on 2021-03-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('folder', models.TextField(unique=True)),
                ('version', models.TextField()),
                ('deployed', models.BooleanField(default=False)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('serial', models.TextField()),
                ('failure_probability', models.IntegerField()),
                ('remaining_lifetime', models.IntegerField(null=True)),
                ('correct', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predictivemodels')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveDataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('folder', models.TextField()),
                ('faulty', models.BooleanField()),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predictivemodels')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('folder', models.TextField(unique=True)),
                ('version', models.TextField()),
                ('deployed', models.BooleanField(default=False)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('serial', models.TextField()),
                ('failure_probability', models.IntegerField()),
                ('correct', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diagnosticsmodels')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticDataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('folder', models.TextField()),
                ('faulty', models.BooleanField()),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diagnosticsmodels')),
            ],
        ),
    ]
